/*
 * LED.c
 *
 * Created: 11/7/2022 10:53:52 AM
 *  Author: carlo
 */ 
#include "LED.h"

void LED_INIT(Uint8 LEDPORT,Uint8 LEDPIN){//output device
	DIO_INIT(LEDPIN,LEDPORT,OUT);	
}
void LED_ON(Uint8 LEDPORT,Uint8 LEDPIN){
	DIO_WRITE(LEDPIN,LEDPORT,HIGH);
}
void LED_OFF(Uint8 LEDPORT,Uint8 LEDPIN){
	DIO_WRITE(LEDPIN,LEDPORT,LOW);
}
void LED_TOGGLE(Uint8 LEDPORT,Uint8 LEDPIN){
	DIO_TOGGLE(LEDPIN,LEDPORT);
}
void LED_TEST(void){
	LED_INIT(LED_NORMAL,LED_RED);
	LED_INIT(LED_PEDESTRIANS,LED_GREEN);
	LED_ON(LED_NORMAL,LED_RED);
	TIMER_delay(5000);
	LED_OFF(LED_NORMAL,LED_RED);
	for (Uint8 i=0;i<10;i++)
	{
		LED_TOGGLE(LED_PEDESTRIANS,LED_GREEN);
		TIMER_delay(500);
	}
	
	
}